version: 0.1

env:
  secrets-manager:
    LOGIN: code-pipeline-sonarqube-cloud-demo:sornatoken
    HOST: code-pipeline-sonarqube-cloud-demo:HOST
    Organization: code-pipeline-sonarqube-cloud-demo:Organization
    Project: code-pipeline-sonarqube-cloud-demo:Project
    CertFileName: code-pipeline-sonarqube-cloud-demo:cert_file_name
    CertS3Uri: cert_s3_uri
phases:
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - mvn package -DskipTests=true
  post_build:
    commands:
      - aws s3 cp $CertS3Uri $CertFileName
      - keytool -import -v -trustcacerts -alias sonarqube -file $CertFileName -keystore ${JAVA_HOME}/lib/security/cacerts -noprompt -storepass changeit
      - sleep 5
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
artifacts:
  files:
    - target/pipeline-demo-0.0.1-SNAPSHOT.jar