version: 0.1

env:
  secrets-manager:
    LOGIN: code-pipeline-sonarqube-cloud-demo:sornatoken
    HOST: code-pipeline-sonarqube-cloud-demo:HOST
    Organization: code-pipeline-sonarqube-cloud-demo:Organization
    Project: code-pipeline-sonarqube-cloud-demo:Project
phases:
  pre_build:
    commands:
      - keytool -import -v -trustcacerts -alias sonarqube -file ca_bundle.crt -keystore ${JAVA_HOME}/jre/lib/security/cacerts -noprompt -storepass changeit
      - sleep 5
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn package -DskipTests=true
artifacts:
  files:
    - target/pipeline-demo-0.0.1-SNAPSHOT.jar